<a href="https://colab.research.google.com/github/krishanpal99/MachineLearning/blob/main/numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook is a hands-on project, completed by me in ***COURSERA***. This notebook covers the basic operations of the two important python libraries known as NumPy and Pandas.

***NumPy*** and ***Pandas*** are two of the most widely used python libraries in Data Science. They offer high-performance, easy to use structures and data analysis tools.

**GUIDED PROJECT LINK:** https://www.coursera.org/projects/python-for-data-analysis-numpy

**ESTIMATED TIME: 1 Hour**

# TASK 1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [ ]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax

# Let's define a one-dimensional array
list = [10,20,30,40,50,60,70]
list

[10, 20, 30, 40, 50, 60, 70]

In [ ]:
# Let's create a numpy array from the list "my_list"
import numpy as np
array = np.array([list])
array

array([[10, 20, 30, 40, 50, 60, 70]])

In [ ]:
type(array)

numpy.ndarray

In [ ]:
# Multi-dimensional (Matrix definition)
multi_dim = np.array([[1,2,3],[4,5,6]])
multi_dim

array([[1, 2, 3],
       [4, 5, 6]])

MINI CHALLENGE #1:
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3]
[4 3 2 2]]
```

In [ ]:
arr1 = np.array([[3, 7, 9, 3],[4, 3, 2, 2]])
print(arr1)

[[3 7 9 3]
 [4 3 2 2]]


# TASK 2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS

In [ ]:
# "rand()" uniform distribution between 0 and 1
random = np.random.rand(20)
random

array([0.73395807, 0.27039152, 0.63945809, 0.02798724, 0.28106951,
       0.33249282, 0.68968979, 0.77272277, 0.3024405 , 0.71432799,
       0.11558098, 0.7514207 , 0.70522934, 0.88189144, 0.2906262 ,
       0.1188034 , 0.93168731, 0.54637973, 0.68970891, 0.0184013 ])

In [ ]:
# you can create a matrix of random number as well
x = np.random.rand(3,3)
x

array([[0.98302927, 0.36839415, 0.66867993],
       [0.77597226, 0.061595  , 0.76066206],
       [0.88466901, 0.06725156, 0.2082212 ]])

In [ ]:
# "randint" is used to generate random integers between upper and lower bounds
num = np.random.randint(1,50)
num

17

In [ ]:
# "randint" can be used to generate a certain number of random itegers as follows
arr = np.random.randint(1,100,17)
arr

array([70, 65,  7,  1, 24, 51, 44,  3,  5, 24, 77, 12,  8, 38,  1, 81, 67],
      dtype=int32)

In [ ]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1,50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
# create a diagonal of ones and zeros everywhere else
i = np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Matrix of ones
one = np.ones((3,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Array of zeros
zero = np.zeros((3,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [ ]:
x = input()
arr = np.random.randint(1,x,10)
arr

array([1, 3, 1, 3, 1, 3, 2, 4, 1, 2], dtype=int32)

# TASK 3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [ ]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y = np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Add 2 numpy arrays together
sum = x+y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
square = x**2
square

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
sqrt = np.sqrt(square)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [ ]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
a = X**2 + Y**2
dist = np.sqrt(a)
dist

array([10.29563014, 16.55294536, 20.39607805])

# TASK 4: PERFORM ARRAYS SLICING AND INDEXING

In [ ]:
np_array = np.array([3,5,6,2,8,10,20,50])
np_array

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [ ]:
# Access specific index from the numpy array
np_array[0]

np.int64(3)

In [ ]:
# Starting from the first index 0 up until and NOT including the last element
np_array[0:8]

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [ ]:
# Broadcasting, altering several values in a numpy array at once
np_array[0:4] = 7
np_array

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [ ]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1,10,(3,3))
matrix

array([[5, 5, 2],
       [1, 6, 3],
       [2, 5, 1]], dtype=int32)

In [ ]:
# Get a row from a matrix
matrix[-1]

array([2, 5, 1], dtype=int32)

In [ ]:
# Get one element
matrix[1][2]

np.int32(3)

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [ ]:
X = np.array([[2, 30, 20, -2, -4] , [3, 4, 40, -3, -2] , [-3, 4, -6, 90, 10] , [25, 45, 34, 22, 12] , [13, 24, 22, 32, 37]])
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK 5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [ ]:
matrix = np.random.randint(1,10,(5,5))
matrix

array([[8, 9, 4, 2, 5],
       [2, 3, 7, 6, 1],
       [9, 1, 4, 2, 4],
       [7, 3, 9, 8, 6],
       [7, 5, 2, 8, 2]], dtype=int32)

In [ ]:
new_matrix = matrix[matrix>7]
new_matrix

array([8, 9, 9, 9, 8, 8], dtype=int32)

In [ ]:
# Obtain odd elements only
odd_matrix = matrix[matrix%2 != 0]
odd_matrix

array([9, 5, 3, 7, 1, 9, 1, 7, 3, 9, 7, 5], dtype=int32)

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
X = np.array([[2, 30, 20, -2, -4] , [3, 4, 40, -3, -2] , [-3, 4, -6, 90, 10] , [25, 45, 34, 22, 12] , [13, 24, 22, 32, 37]])
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [ ]:
X[X<0] = 0
X[X%2 == 1] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK 6: UNDERSTAND PANDAS FUNDAMENTALS

In [ ]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python).
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [ ]:
import pandas as pd

In [ ]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
bank_client_df = pd.DataFrame({'Bank Client ID':[111,222,333,444],
                               'Bank Client Name':['Chanel','Steve','Mitch','Ryan'],
                              'Net Worth':[3500,29000,10000,2000],
                              'Years with Bank':[3,4,9,5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth  Years with Bank
0             111           Chanel       3500                3
1             222            Steve      29000                4
2             333            Mitch      10000                9
3             444             Ryan       2000                5

In [ ]:
# Let's obtain the data type
type(bank_client_df)

pandas.core.frame.DataFrame

In [ ]:
# you can only view the first couple of rows using .head()
bank_client_df.head(2)

Bank Client ID Bank Client Name  Net Worth  Years with Bank
0             111           Chanel       3500                3
1             222            Steve      29000                4

In [ ]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(2)

Bank Client ID Bank Client Name  Net Worth  Years with Bank
2             333            Mitch      10000                9
3             444             Ryan       2000                5

MINI CHALLENGE #6:
- A portfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the portfolio including all stocks

In [ ]:
portfolio_df = pd.DataFrame({'stock ticker symbol':['AAPL','AMSE','RDRT'],
                            'price per share [$]':[3500, 200, 60],
                            'number of stocks':[3,4,7]})
portfolio_df

stock ticker symbol  price per share [$]  number of stocks
0                AAPL                 3500                 3
1                AMSE                  200                 4
2                RDRT                   60                 7

In [ ]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['number of stocks']
stocks_dollar_value

0    10500
1      800
2      420
dtype: int64

In [ ]:
stocks_dollar_value.sum()

np.int64(11720)

# TASK 7: PANDAS WITH CSV/HTML DATA

In [ ]:
# Pandas is used to read a  file and store data in a DataFrame

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html

In [ ]:
import pandas as pd
us_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
us_df

ImportError: Missing optional dependency 'lxml'.  Use pip or conda to install lxml.

# TASK 8: PANDAS OPERATIONS

In [ ]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank Client ID':[111,222,333,444],
                               'Bank Client Name':['Chanel','Steve','Mitch','Ryan'],
                              'Net Worth':[3500,29000,10000,2000],
                              'Years with Bank':[3,4,9,5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth  Years with Bank
0             111           Chanel       3500                3
1             222            Steve      29000                4
2             333            Mitch      10000                9
3             444             Ryan       2000                5

In [ ]:
# Pick certain rows that satisfy a certain criteria
df_loyal = bank_client_df[bank_client_df['Years with Bank']>=5]
df_loyal

Bank Client ID Bank Client Name  Net Worth  Years with Bank
2             333            Mitch      10000                9
3             444             Ryan       2000                5

In [ ]:
# Delete a column from a DataFrame
del bank_client_df['Bank Client ID']
bank_client_df

Bank Client Name  Net Worth  Years with Bank
0           Chanel       3500                3
1            Steve      29000                4
2            Mitch      10000                9
3             Ryan       2000                5

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
high_networth_df = bank_client_df[bank_client_df['Net Worth']>=5000]
high_networth_df

Bank Client Name  Net Worth  Years with Bank
1            Steve      29000                4
2            Mitch      10000                9

In [ ]:
bank_client_df['Net Worth'].sum()

np.int64(44500)

# TASK 9: PANDAS WITH FUNCTIONS

In [ ]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444],
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'],
                               'Net worth [$]':[3500, 29000, 10000, 2000],
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [ ]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity)
def networth_update(balance):
    return balance * 1.2

In [ ]:
# You can apply a function to the DataFrame
bank_client_df['Net worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [ ]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [ ]:
def networth_update(balance):
    return balance * 3 + 200

In [ ]:
result = bank_client_df['Net worth [$]'].apply(networth_update)
result

0    10700
1    87200
2    30200
3     6200
Name: Net worth [$], dtype: int64

In [ ]:
bank_client_df['Net worth [$]'].sum()

np.int64(44500)

# TASK 10: PERFORM SORTING AND ORDERING IN PANDAS

In [ ]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444],
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'],
                               'Net worth [$]':[3500, 29000, 10000, 2000],
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [ ]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by = 'Years with bank')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [ ]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
# Set inplace = True to ensure that change has taken place in memory
# Note that now the change (ordering) took place
bank_client_df.sort_values(by = 'Years with bank',inplace=True)
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK 11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [ ]:
df1 = pd.DataFrame({'A':['A0','A1','A2','A3'],'B':['B0','B1','B2','B3'],
                   'C':['C0','C1','C2','C3'],'D':['D0','D1','D2','D3']}, index = [0,1,2,3])
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
df2 = pd.DataFrame({'A':['A4','A5','A6','A7'],'B':['B4','B5','B6','B7'],
                   'C':['C4','C5','C6','C7'],'D':['D4','D5','D6','D7']}, index = [4,5,6,7])
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
df3 = pd.DataFrame({'A':['A8','A9','A10','A11'],'B':['B8','B9','B10','B11'],
                   'C':['C8','C9','C10','C11'],'D':['D8','D9','D10','D11']}, index = [8,9,10,11])
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [ ]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# TASK 12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers)
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [ ]:
raw_data = {'Bank Client ID': ['1','2','3','4','5'],
            'First Name':['Sheema','Ravi','Ram','Tessa','Guru'],
            'Last Name':['Rao','Takur','Kumar','Andrew','Nath']}
Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID','First Name','Last Name'])
Bank_df_1

Bank Client ID First Name Last Name
0              1     Sheema       Rao
1              2       Ravi     Takur
2              3        Ram     Kumar
3              4      Tessa    Andrew
4              5       Guru      Nath

In [ ]:
raw_data = {'Bank Client ID': ['6','7','8','9','10'],
            'First Name':['Sheethal','Rajesh','Raghu','Arun','Ravi'],
            'Last Name':['Sharma','Thamran','Ram','Vijay','Shastri']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID','First Name','Last Name'])
Bank_df_2

Bank Client ID First Name Last Name
0              6   Sheethal    Sharma
1              7     Rajesh   Thamran
2              8      Raghu       Ram
3              9       Arun     Vijay
4             10       Ravi   Shastri

In [ ]:
raw_data = {'Bank Client ID': ['1','2','3','4','5','6','7','8','9','10'],
            'Annual Salary ($/Year)': [25000, 30000, 54000, 87000, 32000, 76000, 56000, 43000, 27000, 37000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary ($/Year)'])
bank_df_salary

Bank Client ID  Annual Salary ($/Year)
0              1                   25000
1              2                   30000
2              3                   54000
3              4                   87000
4              5                   32000
5              6                   76000
6              7                   56000
7              8                   43000
8              9                   27000
9             10                   37000

In [ ]:
Bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
Bank_df_all

Bank Client ID First Name Last Name
0              1     Sheema       Rao
1              2       Ravi     Takur
2              3        Ram     Kumar
3              4      Tessa    Andrew
4              5       Guru      Nath
0              6   Sheethal    Sharma
1              7     Rajesh   Thamran
2              8      Raghu       Ram
3              9       Arun     Vijay
4             10       Ravi   Shastri

In [ ]:
bank_df_all = pd.merge(Bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all

Bank Client ID First Name Last Name  Annual Salary ($/Year)
0              1     Sheema       Rao                   25000
1              2       Ravi     Takur                   30000
2              3        Ram     Kumar                   54000
3              4      Tessa    Andrew                   87000
4              5       Guru      Nath                   32000
5              6   Sheethal    Sharma                   76000
6              7     Rajesh   Thamran                   56000
7              8      Raghu       Ram                   43000
8              9       Arun     Vijay                   27000
9             10       Ravi   Shastri                   37000

In [ ]:
new_client = {'Bank Client ID':['11'],
             'First Name':'Jeyasri',
             'Last Name':'Senthil',
             'Annual Salary ($/Year)':[100000]}
new_client = pd.DataFrame(new_client, index = [10])
new_client

Bank Client ID First Name Last Name  Annual Salary ($/Year)
10             11    Jeyasri   Senthil                  100000

In [ ]:
pd.concat([bank_df_all, new_client])

Bank Client ID First Name Last Name  Annual Salary ($/Year)
0               1     Sheema       Rao                   25000
1               2       Ravi     Takur                   30000
2               3        Ram     Kumar                   54000
3               4      Tessa    Andrew                   87000
4               5       Guru      Nath                   32000
5               6   Sheethal    Sharma                   76000
6               7     Rajesh   Thamran                   56000
7               8      Raghu       Ram                   43000
8               9       Arun     Vijay                   27000
9              10       Ravi   Shastri                   37000
10             11    Jeyasri   Senthil                  100000